version: "3.9"

services:
  triviaforge:
    image: emancodetemplar/triviaforge:latest
    container_name: triviaforge
    ports:
      - "3000:3000"
    environment:
      - APP_PORT=3000
      - ADMIN_PASSWORD=changeme
      - HOST_IP=
      - SERVER_URL=
    volumes:
      - triviaforge-quizzes:/app/quizzes
      - triviaforge-sessions:/app/sessions
    restart: unless-stopped

volumes:
  triviaforge-quizzes:
  triviaforge-sessions:
